### ISSUE TITLE
Handle timeouts with retry

### ISSUE THREAD

**Issue by trzy** [brilliantlabsAR/noa-assistant#3]
Need to detect timeouts and respond appropriately with retry and/or error. The best way to detect timeouts is to use the streaming completions API and reset the timer for every token received. If no tokens received for e.g. 60 seconds or whatever, retry, or eventually fail with a message.

**Comment by josuah** [comment]
It looks like timeouts errors also happen from the "resend OTP" button:
![](https://cdn.discordapp.com/attachments/1229804586789765202/1229814305617346611/Screenshot_2024-04-16_112244.png?ex=66310cd3&is=661e97d3&hm=04387e2f870bdc9e50183646927be4e5c04efbb815e7e564a788109455b4eb3d&)
